-- MySQL Script generated by MySQL Workbench
-- Mon 07 May 2018 11:07:11 AM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sensoricnet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sensoricnet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sensoricnet` DEFAULT CHARACTER SET utf8 ;
USE `sensoricnet` ;

-- -----------------------------------------------------
-- Table `sensoricnet`.`sensors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sensoricnet`.`sensors` (
  `id` VARCHAR(80) NOT NULL,
  `appId` VARCHAR(16) NULL,
  `devId` VARCHAR(32) NULL,
  `fieldId` VARCHAR(32) NULL,
  `unitType` INT UNSIGNED NULL COMMENT '1 - teplota\n2 - humidity\n3 - pressure\n4 - gps\n5 - prachove castice',
  `unitName` VARCHAR(16) NULL,
  `description` VARCHAR(255) NULL,
  `lastLatitude` FLOAT(10,6) NULL,
  `lastLongitude` FLOAT(10,6) NULL,
  `lastAltitude` INT NULL,
  `lastSeen` DATETIME NULL,
  `lastValueString` VARCHAR(45) NULL,
  `lastValueFloat` FLOAT NULL,
  PRIMARY KEY (`id`),
  INDEX `devId_idx` (`devId` ASC))
ENGINE = InnoDB
COMMENT = 'tabulka senzoru';


-- -----------------------------------------------------
-- Table `sensoricnet`.`values`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sensoricnet`.`values` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `timestamp` DATETIME(6) NULL,
  `sensorId` VARCHAR(80) NULL,
  `valueString` VARCHAR(45) NULL,
  `valueFloat` FLOAT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_values_sensors1_idx` (`sensorId` ASC),
  CONSTRAINT `fk_values_sensors1`
    FOREIGN KEY (`sensorId`)
    REFERENCES `sensoricnet`.`sensors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'tabulka hodnot, hodnota je zvazana s konkretnim senzorem a muze byt siti prenesena pomoci vice gw (tzn. pomoci vice measurementu)';


-- -----------------------------------------------------
-- Table `sensoricnet`.`gateways`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sensoricnet`.`gateways` (
  `id` VARCHAR(128) NOT NULL,
  `type` ENUM('lora', 'nbiot') NOT NULL,
  `description` VARCHAR(254) NULL,
  `lastLatitude` FLOAT(10,6) NULL,
  `lastLongitude` FLOAT(10,6) NULL,
  `lastAltitude` INT NULL,
  `lastSeen` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'tabulka gw';


-- -----------------------------------------------------
-- Table `sensoricnet`.`measurement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sensoricnet`.`measurement` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `gatewayId` VARCHAR(128) NULL,
  `time` DATETIME NOT NULL,
  `channel` VARCHAR(45) NULL,
  `rssi` VARCHAR(45) NULL,
  `snr` VARCHAR(45) NULL,
  `frequency` VARCHAR(45) NULL,
  `modulation` VARCHAR(45) NULL,
  `dataRate` VARCHAR(45) NULL,
  `codingRate` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_measurement_gateways_idx` (`gatewayId` ASC),
  CONSTRAINT `fk_measurement_gateways`
    FOREIGN KEY (`gatewayId`)
    REFERENCES `sensoricnet`.`gateways` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'tabulka mereni (jedna hodnota muze byt odeslana pomoci vice gw)';


-- -----------------------------------------------------
-- Table `sensoricnet`.`gwPositions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sensoricnet`.`gwPositions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `gatewayId` VARCHAR(128) NOT NULL,
  `time` DATETIME NULL,
  `latitude` FLOAT(10,6) NULL,
  `longitude` FLOAT(10,6) NULL,
  `altitude` INT NULL,
  `changed` TINYINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_gwPositions_gateways_idx` (`gatewayId` ASC),
  CONSTRAINT `fk_gwPositions_gateways`
    FOREIGN KEY (`gatewayId`)
    REFERENCES `sensoricnet`.`gateways` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'tabulka poloh';


-- -----------------------------------------------------
-- Table `sensoricnet`.`valuesHasMeasurement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sensoricnet`.`valuesHasMeasurement` (
  `values_id` BIGINT UNSIGNED NOT NULL,
  `measurement_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`values_id`, `measurement_id`),
  INDEX `fk_values_has_measurement_measurement1_idx` (`measurement_id` ASC),
  INDEX `fk_values_has_measurement_values1_idx` (`values_id` ASC),
  CONSTRAINT `fk_values_has_measurement_values1`
    FOREIGN KEY (`values_id`)
    REFERENCES `sensoricnet`.`values` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_values_has_measurement_measurement1`
    FOREIGN KEY (`measurement_id`)
    REFERENCES `sensoricnet`.`measurement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sensoricnet`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sensoricnet`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `surname` VARCHAR(50) NULL,
  `email` VARCHAR(50) NULL,
  `username` VARCHAR(32) NULL,
  `password` VARCHAR(255) NULL,
  `status` TINYINT UNSIGNED NULL,
  `session` VARCHAR(255) NULL,
  `ipaddr` VARCHAR(39) NULL,
  `lasttime` DATETIME NULL,
  `userlevel` TINYINT UNSIGNED NULL,
  `api` TINYINT UNSIGNED NULL,
  `comment` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sensoricnet`.`sensorsPositions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sensoricnet`.`sensorsPositions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sensorDevId` VARCHAR(32) NOT NULL,
  `time` DATETIME NULL,
  `latitude` FLOAT(10,6) NULL,
  `longitude` FLOAT(10,6) NULL,
  `altitude` INT NULL,
  `changed` TINYINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sensorsPositions_sensors_idx` (`sensorDevId` ASC),
  CONSTRAINT `fk_sensorsPositions_sensors`
    FOREIGN KEY (`sensorDevId`)
    REFERENCES `sensoricnet`.`sensors` (`devId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'tabulka poloh';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
