{
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Prach, PM1",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "µg/m³" }
   ],
   "targets": [
    {
     "alias": "pm 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "analog_in_4",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_node", "operator": "=", "value": "sensoricnet-lora-0001" }
     ]
    }
   ]
  },
  {
   "title": "pm 1 [ug/m3]",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "analog_in_4",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_node", "operator": "=", "value": "sensoricnet-lora-0001" }
     ]
    }
   ]
  },
  {
   "title": "Teplota [°C]",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature_1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_node", "operator": "=", "value": "sensoricnet-lora-0001" }
     ]
    }
   ]
  },
  {
   "title": "Prach, PM2,5",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "µg/m³" }
   ],
   "targets": [
    {
     "alias": "pm 2.5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "analog_in_5",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_node", "operator": "=", "value": "sensoricnet-lora-0001" }
     ]
    }
   ]
  },
  {
   "title": "pm 2.5 [ug/m3]",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "analog_in_5",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_node", "operator": "=", "value": "sensoricnet-lora-0001" }
     ]
    }
   ]
  },
  {
   "title": "Tlak [hPa]",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "barometric_pressure_2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_node", "operator": "=", "value": "sensoricnet-lora-0001" }
     ]
    }
   ]
  },
  {
   "title": "Prach, PM10",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "µg/m³" }
   ],
   "targets": [
    {
     "alias": "pm 10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "analog_in_6",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_node", "operator": "=", "value": "sensoricnet-lora-0001" }
     ]
    }
   ]
  },
  {
   "title": "pm 10 [ug/m3]",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "jkjkjkk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "analog_in_6",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_node", "operator": "=", "value": "sensoricnet-lora-0001" }
     ]
    }
   ]
  },
  {
   "title": "Relativni vlhkost [%]",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "relative_humidity_3",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_node", "operator": "=", "value": "sensoricnet-lora-0001" }
     ]
    }
   ]
  },
  {
   "title": "Teplota",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "°C" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature_1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_node", "operator": "=", "value": "sensoricnet-lora-0001" }
     ]
    }
   ]
  },
  {
   "title": "Dust pie chart [ug/m3]",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 17, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "pm 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "analog_in_4",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_node", "operator": "=", "value": "sensoricnet-lora-0001" }
     ]
    },
    {
     "alias": "pm 2.5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "analog_in_5",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_node", "operator": "=", "value": "sensoricnet-lora-0001" }
     ]
    },
    {
     "alias": "pm 10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "analog_in_6",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_node", "operator": "=", "value": "sensoricnet-lora-0001" }
     ]
    }
   ]
  },
  {
   "title": "Tlak",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "hPa" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "barometric_pressure_2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_node", "operator": "=", "value": "sensoricnet-lora-0001" }
     ]
    }
   ]
  },
  {
   "title": "Vlhkost",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent", "label": "%" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "relative_humidity_3",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_node", "operator": "=", "value": "sensoricnet-lora-0001" }
     ]
    }
   ]
  }
 ]
}